name: mimic_google
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pandas
  - keras
  - scikit-learn
  - scikit-image
  - pydicom
  - itkwidgets
  - spacy=2.3
  - pip
  - seaborn
  - jupyterlab
  - holoviews
  - hvplot
  - pip:
    - plaidml
    - google-cloud-storage
    - google-auth
    - ibis-framework[bigquery]==1.4.0
    - medspacy
    - itables
